version: '3'
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - laravel
    ports:
      - 80:80
    volumes:
      - ./:/src

  laravel:
    container_name: "laravel"
    build:
      context: ./docker/php
    depends_on:
      - mysql
    volumes:
      - ./laravel/:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  mysql:
    image: mysql:8.0.33
    command: --max_allowed_packet=32505856
    container_name: "mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=FortuneTelling
    ports:
      - 3306:3306
